added package
swapsoul/frontend pull request #43
Opened 2021-04-02 06:02 UTC by mounikanimmu

2021-04-02 06:03 UTC, davidgladson approved these changes

2021-04-02 08:54 UTC, phoenixnitin requested changes
Please update code according to comments

2021-04-02 08:54 UTC, phoenixnitin commented on src/app/routes/email-verified/email-verified.component.html
> +              <button mat-button onclick="location.href='privacy'" class="foo" >Privacy Policy</button>&nbsp;
what is class foo

2021-04-02 08:54 UTC, phoenixnitin commented on src/app/routes/email-verified/email-verified.component.scss
> +   .foo{
provide better name

2021-04-02 08:54 UTC, phoenixnitin commented on src/app/routes/resetpwd/resetpwd.component.html
> +              style="@import url(https://fonts.googleapis.com/css?family=Rubik:300,400,500,700|Open+Sans:300,400,600,700); font-family: 'Open Sans', sans-serif;">
import into styles or index file, create a class to apply font

2021-04-02 08:54 UTC, phoenixnitin commented on src/app/routes/resetpwd/resetpwd.component.html
> +      style="@import url(https://fonts.googleapis.com/css?family=Rubik:300,400,500,700|Open+Sans:300,400,600,700); font-family: 'Open Sans', sans-serif;">
again, create class to apply this, importing from url should be done in styles or index file

2021-04-02 08:54 UTC, phoenixnitin commented on src/app/routes/resetpwd/resetpwd.component.html
> +                            <td style="height:40px;">&nbsp;</td>
do not do nbsp, remove from everywhere and use padding, margin, min-width or min-height

2021-04-02 08:54 UTC, phoenixnitin commented on src/app/routes/resetpwd/resetpwd.component.html
> +                                <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.2
is it really required to create icon like this

2021-04-02 08:54 UTC, phoenixnitin commented on src/app/routes/resetpwd/resetpwd.component.html
> +                            <td style="height:40px;">&nbsp; </td>
remove nbsp

2021-04-04 15:32 UTC, phoenixnitin approved these changes
Please work on changes, approving for now

2021-04-04 15:42 UTC, merged