Structure
swapsoul/frontend pull request #64
Opened 2021-07-22 19:18 UTC by mounikanimmu

2021-07-23 00:31 UTC, phoenixnitin requested changes
Update the FB client id, in environment files

2021-07-23 00:31 UTC, phoenixnitin commented on src/app/app.module.ts
> +          provider: new FacebookLoginProvider('1197001647431274')
Put this id in environment and environment.production file.

2021-07-24 05:06 UTC, davidgladson approved these changes

2021-08-04 05:44 UTC, phoenixnitin commented on src/app/app.module.ts
> +          provider: new FacebookLoginProvider('1197001647431274')
Resolved by Nitin

2021-08-04 05:44 UTC, phoenixnitin approved these changes

2021-08-04 05:44 UTC, merged